version: 0.0
os: linux
files:
  - source: /
    destination: /var/www/html/sveltekit-test
permissions:
  - object: /var/www/html/sveltekit-test
    pattern: '**'
    owner: ec2-user
    group: ec2-user
hooks:
  BeforeInstall:
    - location: scripts/install_dependencies.sh
      timeout: 300
      runas: ec2-user
  ApplicationStart:
    - location: scripts/start_application.sh
      timeout: 300
      runas: ec2-user
