version: 0.2

phases:
  install:
    runtime-versions:
      nodejs: 16
    commands:
      - echo Entered the install phase...
      - npm install
  pre_build:
    commands:
      - echo Entered the pre_build phase...
      - npm run test
      - npm run test:unit
  build:
    commands:
      - echo Entered the build phase...
      - npm run build
  post_build:
    commands:
      - echo Entered the post_build phase...

artifacts:
  files:
    - '**/*'
  base-directory: 'build'
  name: $AWS_REGION-$(date +%Y-%m-%d)

cache:
  paths:
    - node_modules/
