version: 2.1
jobs:
  test:
    working_directory: ~/repo
    docker:
      - image: cimg/node:18.16.0
    steps:
      - checkout
      - restore_cache:
          keys:
            - v2-deps
      - run:
          name: Install Dependencies
          command: npm install
      - save_cache:
          key: v2-deps
          paths:
            - node_modules
      #   - run:
      #       name: Playwright install
      #       command: |
      #         npx playwright install
      #         sudo npx playwright install-deps
      #   - run:
      #       name: Run playwright tests
      #       command: npm run test
      - run:
          name: Run unit tests
          command: npm run test:unit

  deploy:
    working_directory: ~/repo
    docker:
      - image: cimg/node:18.16.0
    steps:
      - checkout
      - restore_cache:
          keys:
            - v2-deps
      - run:
          name: Install Dependencies
          command: npm install
      - save_cache:
          key: v2-deps
          paths:
            - node_modules
      - run:
          name: Build project
          command: npm run build
      - run:
          name: Install vercel cli
          command: sudo npm i -g vercel
      - run:
          name: Login to vercel
          command: vercel login --token $VERCEL_TOKEN
      - run:
          name: Deploy to vercel
          command: vercel deploy --yes --env KEY1=value1 --env KEY2=value2

workflows:
  test_and_deploy:
    jobs:
      - test
      - deploy
