version: 2.1
jobs:
  build:
    working_directory: ~/repo
    docker:
      - image: cimg/node:18.16.0
    steps:
      - checkout
      - run:
          name: Update NPM
          command: 'sudo npm install -g npm@latest'
      - restore_cache:
          key: dependency-cache-{{ checksum "package-lock.json" }}
      - run:
          name: Install Dependencies
          command: npm install
      - save_cache:
          key: dependency-cache-{{ checksum "package-lock.json" }}
          paths:
            - ./node_modules
      - run:
          name: Playwright install
          command: npx playwright install
      - run:
          name: Playwright dependencies
          command: sudo npx playwright install-deps
      - run:
          name: Run playwright tests
          command: npm run test
      - run:
          name: Run unit tests
          command: npm run test:unit
